version: '3'

services:
  ct-universal-signon:
    depends_on:
      - keycloak-db
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 8888:8888
      - 8080:8080
      - 8443:8443
    environment:
#      KEYCLOAK_IMPORT: /opt/jboss/keycloak_install_stage/realms/ct-realm-local-dev.json
      DEBUG_PORT: 8888
      PROXY_ADDRESS_FORWARDING: 'true'
      JDBC_PARAMS: useSSL=false&allowPublicKeyRetrieval=true

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak.admin
      KC_HOSTNAME_STRICT: false